[package]
name = "subslice-to-array"
version = "0.1.0"
edition = "2021"
rust-version = "1.79"
authors = ["Finley Huggins"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/robofinch/subslice-to-array"
# documention = TODO
# categories = TODO
# keywords = TODO
# description = TODO

[dependencies]
