[package]
name = "subslice-to-array"
version = "0.1.1"
edition = "2021"
rust-version = "1.79"
authors = ["Finley Huggins"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/robofinch/subslice-to-array"
description = "Extract fixed-range subslices as arrays, with compile-time checks"
keywords = ["subslice", "array", "slice", "const", "arrayref"]
categories = ["rust-patterns", "no-std", "no-std::no-alloc"]

[dependencies]
